<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <VersionPrefix>1.1.0</VersionPrefix>
    <Authors>Wiesław Šoltés</Authors>
    <Company>Wiesław Šoltés</Company>
    <Product>RibbonSpace</Product>
    <Copyright>Copyright © 2026 Wiesław Šoltés</Copyright>
    <RepositoryUrl>https://github.com/wieslawsoltes/RibbonSpace</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>
    <PackageProjectUrl>https://github.com/wieslawsoltes/RibbonSpace</PackageProjectUrl>
    <PackageTags>ribbon;fluent;office;toolbar;commandbar;backstage;quick-access-toolbar;keytips;mvvm;uno-platform;winui;webassembly;desktop</PackageTags>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>portable</DebugType>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup Condition="'$(IsPackable)' == 'true'">
    <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="/" Visible="false" />
    <None Include="$(MSBuildThisFileDirectory)build/icon.png" Pack="true" PackagePath="/" Visible="false" />
  </ItemGroup>
</Project>
