#!/usr/bin/env python3
"""Generates the shared IRibbonItem implementation for RibbonSpace item controls.

Run from the repository root:  python3 tools/generate-item-common.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src/RibbonSpace.Uno/Controls/Generated"

CLASSES = [
    # class, default size, abstract
    ("RibbonButton", "Medium"),
    ("RibbonToggleButton", "Small"),
    ("RibbonCheckBox", "Medium"),
    ("RibbonControlBase", "Medium"),
]

PROPS = [
    # name, type, default, callback kind, doc
    ("Id", "string", "null", "id", "Stable id used for persistence, the Quick Access Toolbar, customization and automation (falls back to Name / CommandId)."),
    ("Label", "string", "null", "layout+tip", "Label."),
    ("Icon", "object", "null", "layout", "Icon: glyph, path data, image URI, RibbonIcon, IconSource, IconElement or ImageSource."),
    ("LargeIcon", "object", "null", "layout", "Icon used in the large size (falls back to Icon)."),
    ("Size", "RibbonItemSize", "RibbonItemSize.__DEFAULT__", "layout", "Preferred (largest) size; also selects the default SizeDefinition."),
    ("SizeDefinition", "string", "null", "layout", "Adaptive sizes for the Large, Medium and Small group states, e.g. \"Large, Medium, Small\"."),
    ("CurrentSize", "RibbonItemSize", "RibbonItemSize.__DEFAULT__", "none", "Size currently used (set by the hosting group, toolbar or QAT)."),
    ("IsSimplified", "bool", "false", "none", "True when presented in the simplified line, a toolbar or the QAT."),
    ("ActualShowLabel", "bool", "true", "none", "Effective label visibility for the current layout."),
    ("KeyTip", "string", "null", "tip", "Explicit KeyTip; generated from the label when not set."),
    ("ScreenTip", "object", "null", "tip", "Tooltip: a string (description) or a RibbonScreenTip."),
    ("CommandId", "string", "null", "command", "Id of a command registered in the ribbon command catalog."),
    ("Shortcut", "string", "null", "tip", "Keyboard shortcut shown in the ScreenTip, e.g. \"Ctrl+B\"."),
    ("SimplifiedVisibility", "RibbonSimplifiedVisibility", "RibbonSimplifiedVisibility.Auto", "layout", "Behaviour in the simplified ribbon."),
    ("SimplifiedLabel", "RibbonSimplifiedLabel", "RibbonSimplifiedLabel.Auto", "layout", "Label visibility in the simplified ribbon (Auto shows labels of items whose preferred size is Large)."),
    ("ShowLabel", "bool", "true", "layout", "Shows the label in the medium size."),
    ("CanAddToQuickAccess", "bool", "true", "none", "Allows \"Add to Quick Access Toolbar\"."),
    ("Metrics", "RibbonMetrics", "RibbonMetrics.Comfortable", "none", "Layout metrics in effect."),
]

def nullable(t):
    return t + "?" if t in ("string", "object") else t

def gen(cls, default_size):
    lines = []
    lines.append("// <auto-generated> Generated by tools/generate-item-common.py. Do not edit. </auto-generated>")
    lines.append("#nullable enable")
    lines.append("using Microsoft.UI.Xaml;")
    lines.append("using Microsoft.UI.Xaml.Controls;")
    lines.append("using RibbonSpace.Controls.Primitives;")
    lines.append("using RibbonSpace.Layout;")
    lines.append("")
    lines.append("namespace RibbonSpace.Controls;")
    lines.append("")
    lines.append(f"partial class {cls} : IRibbonItem, IRibbonItemInternal, IRibbonItemEditable")
    lines.append("{")
    for name, typ, default, kind, doc in PROPS:
        d = default.replace("__DEFAULT__", default_size)
        cb = "null" if kind == "none" else f"On{name}Changed"
        lines.append(f"    /// <summary>Identifies <see cref=\"{name}\"/>.</summary>")
        lines.append(f"    public static readonly DependencyProperty {name}Property = DependencyProperty.Register(nameof({name}), typeof({typ}), typeof({cls}), new PropertyMetadata({d}{', ' + cb if cb != 'null' else ''}));")
        lines.append("")
    for name, typ, default, kind, doc in PROPS:
        t = nullable(typ)
        lines.append(f"    /// <summary>{doc}</summary>")
        lines.append(f"    public {t} {name} {{ get => ({t})GetValue({name}Property); set => SetValue({name}Property, value); }}")
        lines.append("")
    for name, typ, default, kind, doc in PROPS:
        if kind == "none":
            continue
        lines.append(f"    private static void On{name}Changed(DependencyObject d, DependencyPropertyChangedEventArgs e)")
        lines.append("    {")
        lines.append(f"        var item = ({cls})d;")
        if name == "Size":
            lines.append("        if (!item._layoutApplied)")
            lines.append("        {")
            lines.append("            item.CurrentSize = item.Size;")
            lines.append("        }")
            lines.append("")
        if "layout" in kind:
            lines.append("        RibbonItemHelper.InvalidateHostLayout(item);")
        if "tip" in kind:
            lines.append("        RibbonItemHelper.UpdateToolTip(item);")
        if name == "Shortcut":
            lines.append("        RibbonItemHelper.ItemsVersion++;")
        if kind == "command":
            lines.append("        RibbonItemHelper.ResolveCommand(item);")
        if kind == "id":
            lines.append("        RibbonItemHelper.UpdateAutomation(item);")
        lines.append("        item.OnRibbonPropertyChanged(e);")
        lines.append("    }")
        lines.append("")
    lines.append("    IReadOnlyList<DependencyProperty> IRibbonItemInternal.LinkedProperties => [LabelProperty, IconProperty, LargeIconProperty, ScreenTipProperty, ShortcutProperty, KeyTipProperty, SizeProperty, SizeDefinitionProperty];")
    lines.append("")
    lines.append("    /// <summary>Called when a common ribbon item property changed.</summary>")
    lines.append("    protected virtual void OnRibbonPropertyChanged(DependencyPropertyChangedEventArgs e)")
    lines.append("    {")
    lines.append("    }")
    lines.append("")
    lines.append("    string? IRibbonItem.Id => RibbonItemHelper.GetId(this, Id, CommandId);")
    lines.append("")
    lines.append("    /// <summary>Effective adaptive size definition.</summary>")
    lines.append("    public RibbonSizeDefinition EffectiveSizeDefinition => RibbonSizeDefinition.TryParse(SizeDefinition, out var definition) ? definition : RibbonSizeDefinition.ForPreferredSize(Size);")
    lines.append("")
    lines.append("    /// <summary>Whether the label is shown in the simplified line.</summary>")
    lines.append("    public bool ShowLabelInSimplifiedMode => SimplifiedLabel switch { RibbonSimplifiedLabel.Show => true, RibbonSimplifiedLabel.Hide => false, _ => Size == RibbonItemSize.Large };")
    lines.append("")
    lines.append("    /// <inheritdoc />")
    lines.append("    public void ApplyLayout(RibbonItemLayout layout)")
    lines.append("    {")
    lines.append("        _layoutApplied = true;")
    lines.append("        Metrics = layout.Metrics;")
    lines.append("        IsSimplified = layout.IsSimplified;")
    lines.append("        CurrentSize = layout.Size;")
    lines.append("        ActualShowLabel = layout.ShowLabel ?? (layout.IsSimplified ? ShowLabelInSimplifiedMode : ShowLabel);")
    lines.append("        OnLayoutApplied(layout);")
    lines.append("    }")
    lines.append("")
    lines.append("    partial void OnLayoutApplied(RibbonItemLayout layout);")
    lines.append("")
    lines.append("    private bool _layoutApplied;")
    lines.append("")
    lines.append("    FrameworkElement? IRibbonItem.CreateLinkedCopy() => CreateLinkedCopyCore();")
    lines.append("")
    lines.append("    IEnumerable<MenuFlyoutItemBase> IRibbonItem.CreateOverflowMenuItems() => CreateOverflowMenuItemsCore();")
    lines.append("")
    lines.append("    RibbonKeyTipResult IRibbonItem.OnKeyTip() => OnKeyTipCore();")
    lines.append("")
    lines.append("    bool IRibbonItem.Invoke() => InvokeCore();")
    lines.append("")
    lines.append("    void IRibbonItemInternal.OnUnlinked() => OnUnlinkedCore();")
    lines.append("")
    lines.append("    private void InitializeRibbonItem()")
    lines.append("    {")
    lines.append("        RibbonTheme.EnsureResources();")
    lines.append("        Loaded += (_, _) => RibbonItemHelper.OnLoaded(this);")
    lines.append("        Unloaded += (_, _) => RibbonItemHelper.OnUnloaded(this);")
    lines.append("        RibbonItemHelper.Attach(this);")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"

OUT.mkdir(parents=True, exist_ok=True)
for cls, size in CLASSES:
    (OUT / f"{cls}.Common.g.cs").write_text(gen(cls, size))
print("generated", len(CLASSES), "files")
